version: 3

env:
  LLVM_VERSION: "15.0.6"

tasks:
  setup:
    dir: libs/llvm
    cmds:
      - wget -nc -O clang_llvm.tar.xz --show-progress "https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-18.04.tar.xz" || true
      - tar --strip-components=1 -xvf clang_llvm.tar.xz
