version: 3

env:
  YARA_VERSION: "v4.2.3"

tasks:
  yara-submodule:
    cmds:
      - git submodule add --force https://github.com/YARA-Java/yara.git submodules/yara
      - git -C submodules/yara checkout $YARA_VERSION

