version: 3

tasks:
  build:
    dir: submodules/jextract
    cmds:
      - gradle -Dorg.gradle.java.home="${GRADLE_JAVA_HOME}" -Pjdk20_home="${JAVA_HOME}" -Pllvm_home="${LLVM_HOME}" clean verify
  test:
    dir: submodules/jextract
    cmds:
      - gradle -Dorg.gradle.java.home="${GRADLE_JAVA_HOME}" -Pjdk20_home="${JAVA_HOME}" -Pllvm_home="${LLVM_HOME}" -Pjtreg_home="${JTREG_HOME}" jtreg
  yara-binding:
    dir: submodules/jextract
    cmds:
      - sh -c "(
        build/jextract/bin/jextract
        -l yara
        --source
        --output "${YARA_JAVA_SRC}"
        --target-package com.virustotal.yara.binding
        "${YARA_HEADERS}/yara.h"
        )"
