// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$149 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$149() {}
    static final FunctionDescriptor __scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __scalblnf$MH = RuntimeHelper.downcallHandle(
        "__scalblnf",
        constants$149.__scalblnf$FUNC
    );
    static final FunctionDescriptor nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nearbyintf$MH = RuntimeHelper.downcallHandle(
        "nearbyintf",
        constants$149.nearbyintf$FUNC
    );
    static final FunctionDescriptor __nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __nearbyintf$MH = RuntimeHelper.downcallHandle(
        "__nearbyintf",
        constants$149.__nearbyintf$FUNC
    );
    static final FunctionDescriptor roundf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle roundf$MH = RuntimeHelper.downcallHandle(
        "roundf",
        constants$149.roundf$FUNC
    );
    static final FunctionDescriptor __roundf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __roundf$MH = RuntimeHelper.downcallHandle(
        "__roundf",
        constants$149.__roundf$FUNC
    );
    static final FunctionDescriptor truncf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle truncf$MH = RuntimeHelper.downcallHandle(
        "truncf",
        constants$149.truncf$FUNC
    );
}


