// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final FunctionDescriptor clock_settime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clock_settime$MH = RuntimeHelper.downcallHandle(
        "clock_settime",
        constants$63.clock_settime$FUNC
    );
    static final FunctionDescriptor clock_nanosleep$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clock_nanosleep$MH = RuntimeHelper.downcallHandle(
        "clock_nanosleep",
        constants$63.clock_nanosleep$FUNC
    );
    static final FunctionDescriptor clock_getcpuclockid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clock_getcpuclockid$MH = RuntimeHelper.downcallHandle(
        "clock_getcpuclockid",
        constants$63.clock_getcpuclockid$FUNC
    );
    static final FunctionDescriptor timer_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_create$MH = RuntimeHelper.downcallHandle(
        "timer_create",
        constants$63.timer_create$FUNC
    );
    static final FunctionDescriptor timer_delete$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_delete$MH = RuntimeHelper.downcallHandle(
        "timer_delete",
        constants$63.timer_delete$FUNC
    );
    static final FunctionDescriptor timer_settime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_settime$MH = RuntimeHelper.downcallHandle(
        "timer_settime",
        constants$63.timer_settime$FUNC
    );
}


