// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final FunctionDescriptor __truncf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __truncf$MH = RuntimeHelper.downcallHandle(
        "__truncf",
        constants$150.__truncf$FUNC
    );
    static final FunctionDescriptor remquof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle remquof$MH = RuntimeHelper.downcallHandle(
        "remquof",
        constants$150.remquof$FUNC
    );
    static final FunctionDescriptor __remquof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __remquof$MH = RuntimeHelper.downcallHandle(
        "__remquof",
        constants$150.__remquof$FUNC
    );
    static final FunctionDescriptor lrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle lrintf$MH = RuntimeHelper.downcallHandle(
        "lrintf",
        constants$150.lrintf$FUNC
    );
    static final FunctionDescriptor __lrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __lrintf$MH = RuntimeHelper.downcallHandle(
        "__lrintf",
        constants$150.__lrintf$FUNC
    );
    static final FunctionDescriptor llrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle llrintf$MH = RuntimeHelper.downcallHandle(
        "llrintf",
        constants$150.llrintf$FUNC
    );
}


