// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final FunctionDescriptor cos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cos$MH = RuntimeHelper.downcallHandle(
        "cos",
        constants$108.cos$FUNC
    );
    static final FunctionDescriptor __cos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __cos$MH = RuntimeHelper.downcallHandle(
        "__cos",
        constants$108.__cos$FUNC
    );
    static final FunctionDescriptor sin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sin$MH = RuntimeHelper.downcallHandle(
        "sin",
        constants$108.sin$FUNC
    );
    static final FunctionDescriptor __sin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __sin$MH = RuntimeHelper.downcallHandle(
        "__sin",
        constants$108.__sin$FUNC
    );
    static final FunctionDescriptor tan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle tan$MH = RuntimeHelper.downcallHandle(
        "tan",
        constants$108.tan$FUNC
    );
    static final FunctionDescriptor __tan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __tan$MH = RuntimeHelper.downcallHandle(
        "__tan",
        constants$108.__tan$FUNC
    );
}


