// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final FunctionDescriptor yr_re_node_append_child$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_node_append_child$MH = RuntimeHelper.downcallHandle(
        "yr_re_node_append_child",
        constants$93.yr_re_node_append_child$FUNC
    );
    static final FunctionDescriptor yr_re_node_prepend_child$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_node_prepend_child$MH = RuntimeHelper.downcallHandle(
        "yr_re_node_prepend_child",
        constants$93.yr_re_node_prepend_child$FUNC
    );
    static final FunctionDescriptor yr_re_exec$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_exec$MH = RuntimeHelper.downcallHandle(
        "yr_re_exec",
        constants$93.yr_re_exec$FUNC
    );
    static final FunctionDescriptor yr_re_fast_exec$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_fast_exec$MH = RuntimeHelper.downcallHandle(
        "yr_re_fast_exec",
        constants$93.yr_re_fast_exec$FUNC
    );
    static final FunctionDescriptor yr_re_parse$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_parse$MH = RuntimeHelper.downcallHandle(
        "yr_re_parse",
        constants$93.yr_re_parse$FUNC
    );
    static final FunctionDescriptor yr_re_parse_hex$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_parse_hex$MH = RuntimeHelper.downcallHandle(
        "yr_re_parse_hex",
        constants$93.yr_re_parse_hex$FUNC
    );
}


