// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final FunctionDescriptor _yr_compiler_pop_file_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_pop_file_name$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_pop_file_name",
        constants$99._yr_compiler_pop_file_name$FUNC
    );
    static final FunctionDescriptor _yr_compiler_get_var_frame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_get_var_frame$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_get_var_frame",
        constants$99._yr_compiler_get_var_frame$FUNC
    );
    static final FunctionDescriptor _yr_compiler_default_include_callback$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_default_include_callback$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_default_include_callback",
        constants$99._yr_compiler_default_include_callback$FUNC
    );
    static final FunctionDescriptor _yr_compiler_get_rule_by_idx$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _yr_compiler_get_rule_by_idx$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_get_rule_by_idx",
        constants$99._yr_compiler_get_rule_by_idx$FUNC
    );
    static final FunctionDescriptor _yr_compiler_store_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_store_string$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_store_string",
        constants$99._yr_compiler_store_string$FUNC
    );
    static final FunctionDescriptor _yr_compiler_store_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_store_data$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_store_data",
        constants$99._yr_compiler_store_data$FUNC
    );
}


