// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    static final FunctionDescriptor pthread_mutexattr_gettype$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_gettype$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_gettype",
        constants$77.pthread_mutexattr_gettype$FUNC
    );
    static final FunctionDescriptor pthread_mutexattr_settype$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_settype$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_settype",
        constants$77.pthread_mutexattr_settype$FUNC
    );
    static final FunctionDescriptor pthread_mutexattr_getprotocol$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_getprotocol$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_getprotocol",
        constants$77.pthread_mutexattr_getprotocol$FUNC
    );
    static final FunctionDescriptor pthread_mutexattr_setprotocol$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_setprotocol$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_setprotocol",
        constants$77.pthread_mutexattr_setprotocol$FUNC
    );
    static final FunctionDescriptor pthread_mutexattr_getprioceiling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_getprioceiling$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_getprioceiling",
        constants$77.pthread_mutexattr_getprioceiling$FUNC
    );
    static final FunctionDescriptor pthread_mutexattr_setprioceiling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_setprioceiling$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_setprioceiling",
        constants$77.pthread_mutexattr_setprioceiling$FUNC
    );
}


