// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$95 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$95() {}
    static final FunctionDescriptor yr_atoms_extract_triplets$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_extract_triplets$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_extract_triplets",
        constants$95.yr_atoms_extract_triplets$FUNC
    );
    static final FunctionDescriptor yr_atoms_heuristic_quality$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_heuristic_quality$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_heuristic_quality",
        constants$95.yr_atoms_heuristic_quality$FUNC
    );
    static final FunctionDescriptor yr_atoms_table_quality$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_table_quality$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_table_quality",
        constants$95.yr_atoms_table_quality$FUNC
    );
    static final FunctionDescriptor yr_atoms_min_quality$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_min_quality$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_min_quality",
        constants$95.yr_atoms_min_quality$FUNC
    );
    static final FunctionDescriptor yr_atoms_list_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_list_destroy$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_list_destroy",
        constants$95.yr_atoms_list_destroy$FUNC
    );
    static final FunctionDescriptor yr_ac_automaton_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_ac_automaton_create$MH = RuntimeHelper.downcallHandle(
        "yr_ac_automaton_create",
        constants$95.yr_ac_automaton_create$FUNC
    );
}


