// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$139 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$139() {}
    static final FunctionDescriptor sqrtf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle sqrtf$MH = RuntimeHelper.downcallHandle(
        "sqrtf",
        constants$139.sqrtf$FUNC
    );
    static final FunctionDescriptor __sqrtf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __sqrtf$MH = RuntimeHelper.downcallHandle(
        "__sqrtf",
        constants$139.__sqrtf$FUNC
    );
    static final FunctionDescriptor hypotf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle hypotf$MH = RuntimeHelper.downcallHandle(
        "hypotf",
        constants$139.hypotf$FUNC
    );
    static final FunctionDescriptor __hypotf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __hypotf$MH = RuntimeHelper.downcallHandle(
        "__hypotf",
        constants$139.__hypotf$FUNC
    );
    static final FunctionDescriptor cbrtf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle cbrtf$MH = RuntimeHelper.downcallHandle(
        "cbrtf",
        constants$139.cbrtf$FUNC
    );
    static final FunctionDescriptor __cbrtf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __cbrtf$MH = RuntimeHelper.downcallHandle(
        "__cbrtf",
        constants$139.__cbrtf$FUNC
    );
}


