// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final FunctionDescriptor pthread_cond_destroy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_cond_destroy$MH = RuntimeHelper.downcallHandle(
        "pthread_cond_destroy",
        constants$81.pthread_cond_destroy$FUNC
    );
    static final FunctionDescriptor pthread_cond_signal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_cond_signal$MH = RuntimeHelper.downcallHandle(
        "pthread_cond_signal",
        constants$81.pthread_cond_signal$FUNC
    );
    static final FunctionDescriptor pthread_cond_broadcast$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_cond_broadcast$MH = RuntimeHelper.downcallHandle(
        "pthread_cond_broadcast",
        constants$81.pthread_cond_broadcast$FUNC
    );
    static final FunctionDescriptor pthread_cond_wait$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_cond_wait$MH = RuntimeHelper.downcallHandle(
        "pthread_cond_wait",
        constants$81.pthread_cond_wait$FUNC
    );
    static final FunctionDescriptor pthread_cond_timedwait$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_cond_timedwait$MH = RuntimeHelper.downcallHandle(
        "pthread_cond_timedwait",
        constants$81.pthread_cond_timedwait$FUNC
    );
    static final FunctionDescriptor pthread_condattr_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_condattr_init$MH = RuntimeHelper.downcallHandle(
        "pthread_condattr_init",
        constants$81.pthread_condattr_init$FUNC
    );
}


