// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$73 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$73() {}
    static final FunctionDescriptor pthread_setschedprio$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_setschedprio$MH = RuntimeHelper.downcallHandle(
        "pthread_setschedprio",
        constants$73.pthread_setschedprio$FUNC
    );
    static final FunctionDescriptor pthread_once$__init_routine$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle pthread_once$__init_routine$MH = RuntimeHelper.downcallHandle(
        constants$73.pthread_once$__init_routine$FUNC
    );
    static final FunctionDescriptor pthread_once$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_once$MH = RuntimeHelper.downcallHandle(
        "pthread_once",
        constants$73.pthread_once$FUNC
    );
    static final FunctionDescriptor pthread_setcancelstate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_setcancelstate$MH = RuntimeHelper.downcallHandle(
        "pthread_setcancelstate",
        constants$73.pthread_setcancelstate$FUNC
    );
    static final FunctionDescriptor pthread_setcanceltype$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_setcanceltype$MH = RuntimeHelper.downcallHandle(
        "pthread_setcanceltype",
        constants$73.pthread_setcanceltype$FUNC
    );
}


