// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final FunctionDescriptor toascii$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle toascii$MH = RuntimeHelper.downcallHandle(
        "toascii",
        constants$47.toascii$FUNC
    );
    static final FunctionDescriptor _toupper$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _toupper$MH = RuntimeHelper.downcallHandle(
        "_toupper",
        constants$47._toupper$FUNC
    );
    static final FunctionDescriptor _tolower$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _tolower$MH = RuntimeHelper.downcallHandle(
        "_tolower",
        constants$47._tolower$FUNC
    );
    static final FunctionDescriptor isalnum_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle isalnum_l$MH = RuntimeHelper.downcallHandle(
        "isalnum_l",
        constants$47.isalnum_l$FUNC
    );
    static final FunctionDescriptor isalpha_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle isalpha_l$MH = RuntimeHelper.downcallHandle(
        "isalpha_l",
        constants$47.isalpha_l$FUNC
    );
    static final FunctionDescriptor iscntrl_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle iscntrl_l$MH = RuntimeHelper.downcallHandle(
        "iscntrl_l",
        constants$47.iscntrl_l$FUNC
    );
}


