// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final FunctionDescriptor timer_gettime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_gettime$MH = RuntimeHelper.downcallHandle(
        "timer_gettime",
        constants$64.timer_gettime$FUNC
    );
    static final FunctionDescriptor timer_getoverrun$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_getoverrun$MH = RuntimeHelper.downcallHandle(
        "timer_getoverrun",
        constants$64.timer_getoverrun$FUNC
    );
    static final FunctionDescriptor timespec_get$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle timespec_get$MH = RuntimeHelper.downcallHandle(
        "timespec_get",
        constants$64.timespec_get$FUNC
    );
    static final FunctionDescriptor gettimeofday$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gettimeofday$MH = RuntimeHelper.downcallHandle(
        "gettimeofday",
        constants$64.gettimeofday$FUNC
    );
    static final FunctionDescriptor settimeofday$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle settimeofday$MH = RuntimeHelper.downcallHandle(
        "settimeofday",
        constants$64.settimeofday$FUNC
    );
    static final FunctionDescriptor adjtime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adjtime$MH = RuntimeHelper.downcallHandle(
        "adjtime",
        constants$64.adjtime$FUNC
    );
}


