// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final FunctionDescriptor yr_stopwatch_elapsed_ns$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_stopwatch_elapsed_ns$MH = RuntimeHelper.downcallHandle(
        "yr_stopwatch_elapsed_ns",
        constants$66.yr_stopwatch_elapsed_ns$FUNC
    );
    static final FunctionDescriptor __sched_cpucount$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sched_cpucount$MH = RuntimeHelper.downcallHandle(
        "__sched_cpucount",
        constants$66.__sched_cpucount$FUNC
    );
    static final FunctionDescriptor __sched_cpualloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __sched_cpualloc$MH = RuntimeHelper.downcallHandle(
        "__sched_cpualloc",
        constants$66.__sched_cpualloc$FUNC
    );
    static final FunctionDescriptor __sched_cpufree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sched_cpufree$MH = RuntimeHelper.downcallHandle(
        "__sched_cpufree",
        constants$66.__sched_cpufree$FUNC
    );
    static final FunctionDescriptor sched_setparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_setparam$MH = RuntimeHelper.downcallHandle(
        "sched_setparam",
        constants$66.sched_setparam$FUNC
    );
    static final FunctionDescriptor sched_getparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_getparam$MH = RuntimeHelper.downcallHandle(
        "sched_getparam",
        constants$66.sched_getparam$FUNC
    );
}


