// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$148() {}
    static final FunctionDescriptor __remainderf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __remainderf$MH = RuntimeHelper.downcallHandle(
        "__remainderf",
        constants$148.__remainderf$FUNC
    );
    static final FunctionDescriptor scalbnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle scalbnf$MH = RuntimeHelper.downcallHandle(
        "scalbnf",
        constants$148.scalbnf$FUNC
    );
    static final FunctionDescriptor __scalbnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __scalbnf$MH = RuntimeHelper.downcallHandle(
        "__scalbnf",
        constants$148.__scalbnf$FUNC
    );
    static final FunctionDescriptor ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle ilogbf$MH = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$148.ilogbf$FUNC
    );
    static final FunctionDescriptor __ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __ilogbf$MH = RuntimeHelper.downcallHandle(
        "__ilogbf",
        constants$148.__ilogbf$FUNC
    );
    static final FunctionDescriptor scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle scalblnf$MH = RuntimeHelper.downcallHandle(
        "scalblnf",
        constants$148.scalblnf$FUNC
    );
}


