// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final FunctionDescriptor strlcat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strlcat$MH = RuntimeHelper.downcallHandle(
        "strlcat",
        constants$43.strlcat$FUNC
    );
    static final FunctionDescriptor memmem$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle memmem$MH = RuntimeHelper.downcallHandle(
        "memmem",
        constants$43.memmem$FUNC
    );
    static final FunctionDescriptor strnlen_w$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strnlen_w$MH = RuntimeHelper.downcallHandle(
        "strnlen_w",
        constants$43.strnlen_w$FUNC
    );
    static final FunctionDescriptor strcmp_w$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strcmp_w$MH = RuntimeHelper.downcallHandle(
        "strcmp_w",
        constants$43.strcmp_w$FUNC
    );
    static final FunctionDescriptor strlcpy_w$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strlcpy_w$MH = RuntimeHelper.downcallHandle(
        "strlcpy_w",
        constants$43.strlcpy_w$FUNC
    );
    static final FunctionDescriptor yr_isalnum$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_isalnum$MH = RuntimeHelper.downcallHandle(
        "yr_isalnum",
        constants$43.yr_isalnum$FUNC
    );
}


