// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final FunctionDescriptor yr_rules_load$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_load$MH = RuntimeHelper.downcallHandle(
        "yr_rules_load",
        constants$158.yr_rules_load$FUNC
    );
    static final FunctionDescriptor yr_rules_load_stream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_load_stream$MH = RuntimeHelper.downcallHandle(
        "yr_rules_load_stream",
        constants$158.yr_rules_load_stream$FUNC
    );
    static final FunctionDescriptor yr_rules_destroy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_destroy$MH = RuntimeHelper.downcallHandle(
        "yr_rules_destroy",
        constants$158.yr_rules_destroy$FUNC
    );
    static final FunctionDescriptor yr_rules_define_integer_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_rules_define_integer_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_integer_variable",
        constants$158.yr_rules_define_integer_variable$FUNC
    );
    static final FunctionDescriptor yr_rules_define_boolean_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_define_boolean_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_boolean_variable",
        constants$158.yr_rules_define_boolean_variable$FUNC
    );
    static final FunctionDescriptor yr_rules_define_float_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle yr_rules_define_float_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_float_variable",
        constants$158.yr_rules_define_float_variable$FUNC
    );
}


