// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final FunctionDescriptor yr_arena_get_ptr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_arena_get_ptr$MH = RuntimeHelper.downcallHandle(
        "yr_arena_get_ptr",
        constants$52.yr_arena_get_ptr$FUNC
    );
    static final FunctionDescriptor yr_arena_get_current_offset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_arena_get_current_offset$MH = RuntimeHelper.downcallHandle(
        "yr_arena_get_current_offset",
        constants$52.yr_arena_get_current_offset$FUNC
    );
    static final FunctionDescriptor yr_arena_allocate_memory$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_allocate_memory$MH = RuntimeHelper.downcallHandle(
        "yr_arena_allocate_memory",
        constants$52.yr_arena_allocate_memory$FUNC
    );
    static final FunctionDescriptor yr_arena_allocate_zeroed_memory$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_allocate_zeroed_memory$MH = RuntimeHelper.downcallHandle(
        "yr_arena_allocate_zeroed_memory",
        constants$52.yr_arena_allocate_zeroed_memory$FUNC
    );
    static final FunctionDescriptor yr_arena_allocate_struct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_allocate_struct$MH = RuntimeHelper.downcallHandleVariadic(
        "yr_arena_allocate_struct",
        constants$52.yr_arena_allocate_struct$FUNC
    );
    static final FunctionDescriptor yr_arena_make_ptr_relocatable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_arena_make_ptr_relocatable$MH = RuntimeHelper.downcallHandleVariadic(
        "yr_arena_make_ptr_relocatable",
        constants$52.yr_arena_make_ptr_relocatable$FUNC
    );
}


