// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final FunctionDescriptor yr_compiler_define_integer_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_compiler_define_integer_variable$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_define_integer_variable",
        constants$102.yr_compiler_define_integer_variable$FUNC
    );
    static final FunctionDescriptor yr_compiler_define_boolean_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_compiler_define_boolean_variable$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_define_boolean_variable",
        constants$102.yr_compiler_define_boolean_variable$FUNC
    );
    static final FunctionDescriptor yr_compiler_define_float_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle yr_compiler_define_float_variable$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_define_float_variable",
        constants$102.yr_compiler_define_float_variable$FUNC
    );
    static final FunctionDescriptor yr_compiler_define_string_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_define_string_variable$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_define_string_variable",
        constants$102.yr_compiler_define_string_variable$FUNC
    );
    static final FunctionDescriptor yr_compiler_get_rules$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_get_rules$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_get_rules",
        constants$102.yr_compiler_get_rules$FUNC
    );
    static final FunctionDescriptor yr_initialize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle yr_initialize$MH = RuntimeHelper.downcallHandle(
        "yr_initialize",
        constants$102.yr_initialize$FUNC
    );
}


