// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$155 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$155() {}
    static final FunctionDescriptor yr_scanner_define_string_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_define_string_variable$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_define_string_variable",
        constants$155.yr_scanner_define_string_variable$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_mem_blocks$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_mem_blocks$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_mem_blocks",
        constants$155.yr_scanner_scan_mem_blocks$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_mem$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_mem$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_mem",
        constants$155.yr_scanner_scan_mem$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_file$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_file",
        constants$155.yr_scanner_scan_file$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_fd$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_fd",
        constants$155.yr_scanner_scan_fd$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_proc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_proc$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_proc",
        constants$155.yr_scanner_scan_proc$FUNC
    );
}


