// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final FunctionDescriptor pthread_atfork$__prepare$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle pthread_atfork$__prepare$MH = RuntimeHelper.downcallHandle(
        constants$86.pthread_atfork$__prepare$FUNC
    );
    static final FunctionDescriptor pthread_atfork$__parent$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle pthread_atfork$__parent$MH = RuntimeHelper.downcallHandle(
        constants$86.pthread_atfork$__parent$FUNC
    );
    static final FunctionDescriptor pthread_atfork$__child$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle pthread_atfork$__child$MH = RuntimeHelper.downcallHandle(
        constants$86.pthread_atfork$__child$FUNC
    );
}


