// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final FunctionDescriptor __lgamma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __lgamma$MH = RuntimeHelper.downcallHandle(
        "__lgamma",
        constants$122.__lgamma$FUNC
    );
    static final FunctionDescriptor tgamma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle tgamma$MH = RuntimeHelper.downcallHandle(
        "tgamma",
        constants$122.tgamma$FUNC
    );
    static final FunctionDescriptor __tgamma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __tgamma$MH = RuntimeHelper.downcallHandle(
        "__tgamma",
        constants$122.__tgamma$FUNC
    );
    static final FunctionDescriptor gamma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gamma$MH = RuntimeHelper.downcallHandle(
        "gamma",
        constants$122.gamma$FUNC
    );
    static final FunctionDescriptor __gamma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __gamma$MH = RuntimeHelper.downcallHandle(
        "__gamma",
        constants$122.__gamma$FUNC
    );
    static final FunctionDescriptor lgamma_r$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lgamma_r$MH = RuntimeHelper.downcallHandle(
        "lgamma_r",
        constants$122.lgamma_r$FUNC
    );
}


