// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*pthread_atfork$__prepare)();
 * }
 */
public interface pthread_atfork$__prepare {

    void apply();
    static MemorySegment allocate(pthread_atfork$__prepare fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(pthread_atfork$__prepare.class, fi, constants$86.pthread_atfork$__prepare$FUNC, scope);
    }
    static pthread_atfork$__prepare ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return () -> {
            try {
                constants$86.pthread_atfork$__prepare$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


