// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct RE_AST {
 *     uint32_t flags;
 *     RE_NODE* root_node;
 * };
 * }
 */
public class RE_AST {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("flags"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("root_node")
    ).withName("RE_AST");
    public static MemoryLayout $LAYOUT() {
        return RE_AST.$struct$LAYOUT;
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return RE_AST.flags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)RE_AST.flags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        RE_AST.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)RE_AST.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        RE_AST.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle root_node$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("root_node"));
    public static VarHandle root_node$VH() {
        return RE_AST.root_node$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * RE_NODE* root_node;
     * }
     */
    public static MemorySegment root_node$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)RE_AST.root_node$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * RE_NODE* root_node;
     * }
     */
    public static void root_node$set(MemorySegment seg, MemorySegment x) {
        RE_AST.root_node$VH.set(seg, x);
    }
    public static MemorySegment root_node$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)RE_AST.root_node$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void root_node$set(MemorySegment seg, long index, MemorySegment x) {
        RE_AST.root_node$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


