// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * char* (*YR_COMPILER_INCLUDE_CALLBACK_FUNC)(char* include_name,char* calling_rule_filename,char* calling_rule_namespace,void* user_data);
 * }
 */
public interface YR_COMPILER_INCLUDE_CALLBACK_FUNC {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment include_name, java.lang.foreign.MemorySegment calling_rule_filename, java.lang.foreign.MemorySegment calling_rule_namespace, java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(YR_COMPILER_INCLUDE_CALLBACK_FUNC fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(YR_COMPILER_INCLUDE_CALLBACK_FUNC.class, fi, constants$97.YR_COMPILER_INCLUDE_CALLBACK_FUNC$FUNC, scope);
    }
    static YR_COMPILER_INCLUDE_CALLBACK_FUNC ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _include_name, java.lang.foreign.MemorySegment _calling_rule_filename, java.lang.foreign.MemorySegment _calling_rule_namespace, java.lang.foreign.MemorySegment _user_data) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$98.YR_COMPILER_INCLUDE_CALLBACK_FUNC$MH.invokeExact(symbol, _include_name, _calling_rule_filename, _calling_rule_namespace, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


