// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*YR_COMPILER_RE_AST_CALLBACK_FUNC)(struct YR_RULE* rule,char* string_identifier,struct RE_AST* re_ast,void* user_data);
 * }
 */
public interface YR_COMPILER_RE_AST_CALLBACK_FUNC {

    void apply(java.lang.foreign.MemorySegment rule, java.lang.foreign.MemorySegment string_identifier, java.lang.foreign.MemorySegment re_ast, java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(YR_COMPILER_RE_AST_CALLBACK_FUNC fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(YR_COMPILER_RE_AST_CALLBACK_FUNC.class, fi, constants$98.YR_COMPILER_RE_AST_CALLBACK_FUNC$FUNC, scope);
    }
    static YR_COMPILER_RE_AST_CALLBACK_FUNC ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _rule, java.lang.foreign.MemorySegment _string_identifier, java.lang.foreign.MemorySegment _re_ast, java.lang.foreign.MemorySegment _user_data) -> {
            try {
                constants$98.YR_COMPILER_RE_AST_CALLBACK_FUNC$MH.invokeExact(symbol, _rule, _string_identifier, _re_ast, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


