// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _YR_FIXUP YR_FIXUP;
 * }
 */
public final class YR_FIXUP extends _YR_FIXUP {

    // Suppresses default constructor, ensuring non-instantiability.
    private YR_FIXUP() {}
}


