// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_INT_ENUM_ITERATOR {
 *     int64_t next;
 *     int64_t count;
 *     int64_t items[1];
 * };
 * }
 */
public class YR_INT_ENUM_ITERATOR {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("next"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("count"),
        MemoryLayout.sequenceLayout(1, Constants$root.C_LONG_LONG$LAYOUT).withName("items")
    ).withName("YR_INT_ENUM_ITERATOR");
    public static MemoryLayout $LAYOUT() {
        return YR_INT_ENUM_ITERATOR.$struct$LAYOUT;
    }
    static final VarHandle next$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("next"));
    public static VarHandle next$VH() {
        return YR_INT_ENUM_ITERATOR.next$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t next;
     * }
     */
    public static long next$get(MemorySegment seg) {
        return (long)YR_INT_ENUM_ITERATOR.next$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t next;
     * }
     */
    public static void next$set(MemorySegment seg, long x) {
        YR_INT_ENUM_ITERATOR.next$VH.set(seg, x);
    }
    public static long next$get(MemorySegment seg, long index) {
        return (long)YR_INT_ENUM_ITERATOR.next$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void next$set(MemorySegment seg, long index, long x) {
        YR_INT_ENUM_ITERATOR.next$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("count"));
    public static VarHandle count$VH() {
        return YR_INT_ENUM_ITERATOR.count$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t count;
     * }
     */
    public static long count$get(MemorySegment seg) {
        return (long)YR_INT_ENUM_ITERATOR.count$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t count;
     * }
     */
    public static void count$set(MemorySegment seg, long x) {
        YR_INT_ENUM_ITERATOR.count$VH.set(seg, x);
    }
    public static long count$get(MemorySegment seg, long index) {
        return (long)YR_INT_ENUM_ITERATOR.count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, long x) {
        YR_INT_ENUM_ITERATOR.count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment items$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


