// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_MATCHES {
 *     YR_MATCH* head;
 *     YR_MATCH* tail;
 *     int32_t count;
 * };
 * }
 */
public class YR_MATCHES {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("head"),
        Constants$root.C_POINTER$LAYOUT.withName("tail"),
        Constants$root.C_INT$LAYOUT.withName("count"),
        MemoryLayout.paddingLayout(32)
    ).withName("YR_MATCHES");
    public static MemoryLayout $LAYOUT() {
        return YR_MATCHES.$struct$LAYOUT;
    }
    static final VarHandle head$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("head"));
    public static VarHandle head$VH() {
        return YR_MATCHES.head$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_MATCH* head;
     * }
     */
    public static MemorySegment head$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_MATCHES.head$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_MATCH* head;
     * }
     */
    public static void head$set(MemorySegment seg, MemorySegment x) {
        YR_MATCHES.head$VH.set(seg, x);
    }
    public static MemorySegment head$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_MATCHES.head$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void head$set(MemorySegment seg, long index, MemorySegment x) {
        YR_MATCHES.head$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle tail$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tail"));
    public static VarHandle tail$VH() {
        return YR_MATCHES.tail$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_MATCH* tail;
     * }
     */
    public static MemorySegment tail$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_MATCHES.tail$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_MATCH* tail;
     * }
     */
    public static void tail$set(MemorySegment seg, MemorySegment x) {
        YR_MATCHES.tail$VH.set(seg, x);
    }
    public static MemorySegment tail$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_MATCHES.tail$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tail$set(MemorySegment seg, long index, MemorySegment x) {
        YR_MATCHES.tail$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("count"));
    public static VarHandle count$VH() {
        return YR_MATCHES.count$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t count;
     * }
     */
    public static int count$get(MemorySegment seg) {
        return (int)YR_MATCHES.count$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t count;
     * }
     */
    public static void count$set(MemorySegment seg, int x) {
        YR_MATCHES.count$VH.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)YR_MATCHES.count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        YR_MATCHES.count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


