// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_RULES {
 *     YR_ARENA* arena;
 *     union {
 *         YR_RULE* rules_table;
 *         YR_RULE* rules_list_head;
 *     };
 *     union {
 *         YR_STRING* strings_table;
 *         YR_STRING* strings_list_head;
 *     };
 *     union {
 *         YR_EXTERNAL_VARIABLE* ext_vars_table;
 *         YR_EXTERNAL_VARIABLE* externals_list_head;
 *     };
 *     YR_AC_TRANSITION* ac_transition_table;
 *     YR_AC_MATCH* ac_match_pool;
 *     uint32_t* ac_match_table;
 *     const uint8_t* code_start;
 *     uint32_t num_rules;
 *     uint32_t num_strings;
 *     uint32_t num_namespaces;
 * };
 * }
 */
public class YR_RULES {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("arena"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("rules_table"),
            Constants$root.C_POINTER$LAYOUT.withName("rules_list_head")
        ).withName("$anon$0"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("strings_table"),
            Constants$root.C_POINTER$LAYOUT.withName("strings_list_head")
        ).withName("$anon$1"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ext_vars_table"),
            Constants$root.C_POINTER$LAYOUT.withName("externals_list_head")
        ).withName("$anon$2"),
        Constants$root.C_POINTER$LAYOUT.withName("ac_transition_table"),
        Constants$root.C_POINTER$LAYOUT.withName("ac_match_pool"),
        Constants$root.C_POINTER$LAYOUT.withName("ac_match_table"),
        Constants$root.C_POINTER$LAYOUT.withName("code_start"),
        Constants$root.C_INT$LAYOUT.withName("num_rules"),
        Constants$root.C_INT$LAYOUT.withName("num_strings"),
        Constants$root.C_INT$LAYOUT.withName("num_namespaces"),
        MemoryLayout.paddingLayout(32)
    ).withName("YR_RULES");
    public static MemoryLayout $LAYOUT() {
        return YR_RULES.$struct$LAYOUT;
    }
    static final VarHandle arena$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("arena"));
    public static VarHandle arena$VH() {
        return YR_RULES.arena$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_ARENA* arena;
     * }
     */
    public static MemorySegment arena$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.arena$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_ARENA* arena;
     * }
     */
    public static void arena$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.arena$VH.set(seg, x);
    }
    public static MemorySegment arena$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.arena$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void arena$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.arena$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle rules_table$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("rules_table"));
    public static VarHandle rules_table$VH() {
        return YR_RULES.rules_table$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_RULE* rules_table;
     * }
     */
    public static MemorySegment rules_table$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.rules_table$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_RULE* rules_table;
     * }
     */
    public static void rules_table$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.rules_table$VH.set(seg, x);
    }
    public static MemorySegment rules_table$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.rules_table$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rules_table$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.rules_table$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle rules_list_head$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("rules_list_head"));
    public static VarHandle rules_list_head$VH() {
        return YR_RULES.rules_list_head$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_RULE* rules_list_head;
     * }
     */
    public static MemorySegment rules_list_head$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.rules_list_head$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_RULE* rules_list_head;
     * }
     */
    public static void rules_list_head$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.rules_list_head$VH.set(seg, x);
    }
    public static MemorySegment rules_list_head$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.rules_list_head$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rules_list_head$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.rules_list_head$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strings_table$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$1"), MemoryLayout.PathElement.groupElement("strings_table"));
    public static VarHandle strings_table$VH() {
        return YR_RULES.strings_table$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_STRING* strings_table;
     * }
     */
    public static MemorySegment strings_table$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.strings_table$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_STRING* strings_table;
     * }
     */
    public static void strings_table$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.strings_table$VH.set(seg, x);
    }
    public static MemorySegment strings_table$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.strings_table$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strings_table$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.strings_table$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strings_list_head$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$1"), MemoryLayout.PathElement.groupElement("strings_list_head"));
    public static VarHandle strings_list_head$VH() {
        return YR_RULES.strings_list_head$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_STRING* strings_list_head;
     * }
     */
    public static MemorySegment strings_list_head$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.strings_list_head$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_STRING* strings_list_head;
     * }
     */
    public static void strings_list_head$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.strings_list_head$VH.set(seg, x);
    }
    public static MemorySegment strings_list_head$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.strings_list_head$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strings_list_head$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.strings_list_head$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ext_vars_table$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("ext_vars_table"));
    public static VarHandle ext_vars_table$VH() {
        return YR_RULES.ext_vars_table$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_EXTERNAL_VARIABLE* ext_vars_table;
     * }
     */
    public static MemorySegment ext_vars_table$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ext_vars_table$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_EXTERNAL_VARIABLE* ext_vars_table;
     * }
     */
    public static void ext_vars_table$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.ext_vars_table$VH.set(seg, x);
    }
    public static MemorySegment ext_vars_table$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ext_vars_table$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ext_vars_table$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.ext_vars_table$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle externals_list_head$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("externals_list_head"));
    public static VarHandle externals_list_head$VH() {
        return YR_RULES.externals_list_head$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_EXTERNAL_VARIABLE* externals_list_head;
     * }
     */
    public static MemorySegment externals_list_head$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.externals_list_head$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_EXTERNAL_VARIABLE* externals_list_head;
     * }
     */
    public static void externals_list_head$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.externals_list_head$VH.set(seg, x);
    }
    public static MemorySegment externals_list_head$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.externals_list_head$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void externals_list_head$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.externals_list_head$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ac_transition_table$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ac_transition_table"));
    public static VarHandle ac_transition_table$VH() {
        return YR_RULES.ac_transition_table$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_AC_TRANSITION* ac_transition_table;
     * }
     */
    public static MemorySegment ac_transition_table$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_transition_table$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_AC_TRANSITION* ac_transition_table;
     * }
     */
    public static void ac_transition_table$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.ac_transition_table$VH.set(seg, x);
    }
    public static MemorySegment ac_transition_table$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_transition_table$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ac_transition_table$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.ac_transition_table$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ac_match_pool$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ac_match_pool"));
    public static VarHandle ac_match_pool$VH() {
        return YR_RULES.ac_match_pool$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_AC_MATCH* ac_match_pool;
     * }
     */
    public static MemorySegment ac_match_pool$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_match_pool$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_AC_MATCH* ac_match_pool;
     * }
     */
    public static void ac_match_pool$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.ac_match_pool$VH.set(seg, x);
    }
    public static MemorySegment ac_match_pool$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_match_pool$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ac_match_pool$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.ac_match_pool$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ac_match_table$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ac_match_table"));
    public static VarHandle ac_match_table$VH() {
        return YR_RULES.ac_match_table$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t* ac_match_table;
     * }
     */
    public static MemorySegment ac_match_table$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_match_table$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t* ac_match_table;
     * }
     */
    public static void ac_match_table$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.ac_match_table$VH.set(seg, x);
    }
    public static MemorySegment ac_match_table$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.ac_match_table$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ac_match_table$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.ac_match_table$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle code_start$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("code_start"));
    public static VarHandle code_start$VH() {
        return YR_RULES.code_start$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const uint8_t* code_start;
     * }
     */
    public static MemorySegment code_start$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULES.code_start$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const uint8_t* code_start;
     * }
     */
    public static void code_start$set(MemorySegment seg, MemorySegment x) {
        YR_RULES.code_start$VH.set(seg, x);
    }
    public static MemorySegment code_start$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULES.code_start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void code_start$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULES.code_start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle num_rules$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_rules"));
    public static VarHandle num_rules$VH() {
        return YR_RULES.num_rules$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t num_rules;
     * }
     */
    public static int num_rules$get(MemorySegment seg) {
        return (int)YR_RULES.num_rules$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t num_rules;
     * }
     */
    public static void num_rules$set(MemorySegment seg, int x) {
        YR_RULES.num_rules$VH.set(seg, x);
    }
    public static int num_rules$get(MemorySegment seg, long index) {
        return (int)YR_RULES.num_rules$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_rules$set(MemorySegment seg, long index, int x) {
        YR_RULES.num_rules$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle num_strings$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_strings"));
    public static VarHandle num_strings$VH() {
        return YR_RULES.num_strings$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t num_strings;
     * }
     */
    public static int num_strings$get(MemorySegment seg) {
        return (int)YR_RULES.num_strings$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t num_strings;
     * }
     */
    public static void num_strings$set(MemorySegment seg, int x) {
        YR_RULES.num_strings$VH.set(seg, x);
    }
    public static int num_strings$get(MemorySegment seg, long index) {
        return (int)YR_RULES.num_strings$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_strings$set(MemorySegment seg, long index, int x) {
        YR_RULES.num_strings$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle num_namespaces$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_namespaces"));
    public static VarHandle num_namespaces$VH() {
        return YR_RULES.num_namespaces$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t num_namespaces;
     * }
     */
    public static int num_namespaces$get(MemorySegment seg) {
        return (int)YR_RULES.num_namespaces$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t num_namespaces;
     * }
     */
    public static void num_namespaces$set(MemorySegment seg, int x) {
        YR_RULES.num_namespaces$VH.set(seg, x);
    }
    public static int num_namespaces$get(MemorySegment seg, long index) {
        return (int)YR_RULES.num_namespaces$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_namespaces$set(MemorySegment seg, long index, int x) {
        YR_RULES.num_namespaces$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


