// Generated by jextract

package com.virustotal.yara.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _YR_STOPWATCH YR_STOPWATCH;
 * }
 */
public final class YR_STOPWATCH extends _YR_STOPWATCH {

    // Suppresses default constructor, ensuring non-instantiability.
    private YR_STOPWATCH() {}
}


