// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$133() {}
    static final FunctionDescriptor coshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle coshf$MH = RuntimeHelper.downcallHandle(
        "coshf",
        constants$133.coshf$FUNC
    );
    static final FunctionDescriptor __coshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __coshf$MH = RuntimeHelper.downcallHandle(
        "__coshf",
        constants$133.__coshf$FUNC
    );
    static final FunctionDescriptor sinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle sinhf$MH = RuntimeHelper.downcallHandle(
        "sinhf",
        constants$133.sinhf$FUNC
    );
    static final FunctionDescriptor __sinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __sinhf$MH = RuntimeHelper.downcallHandle(
        "__sinhf",
        constants$133.__sinhf$FUNC
    );
    static final FunctionDescriptor tanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle tanhf$MH = RuntimeHelper.downcallHandle(
        "tanhf",
        constants$133.tanhf$FUNC
    );
    static final FunctionDescriptor __tanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __tanhf$MH = RuntimeHelper.downcallHandle(
        "__tanhf",
        constants$133.__tanhf$FUNC
    );
}


