// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final FunctionDescriptor yr_re_ast_extract_literal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_extract_literal$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_extract_literal",
        constants$92.yr_re_ast_extract_literal$FUNC
    );
    static final FunctionDescriptor yr_re_ast_has_unbounded_quantifier_for_dot$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_has_unbounded_quantifier_for_dot$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_has_unbounded_quantifier_for_dot",
        constants$92.yr_re_ast_has_unbounded_quantifier_for_dot$FUNC
    );
    static final FunctionDescriptor yr_re_ast_split_at_chaining_point$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_split_at_chaining_point$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_split_at_chaining_point",
        constants$92.yr_re_ast_split_at_chaining_point$FUNC
    );
    static final FunctionDescriptor yr_re_ast_emit_code$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_re_ast_emit_code$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_emit_code",
        constants$92.yr_re_ast_emit_code$FUNC
    );
    static final FunctionDescriptor yr_re_node_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_re_node_create$MH = RuntimeHelper.downcallHandle(
        "yr_re_node_create",
        constants$92.yr_re_node_create$FUNC
    );
    static final FunctionDescriptor yr_re_node_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_node_destroy$MH = RuntimeHelper.downcallHandle(
        "yr_re_node_destroy",
        constants$92.yr_re_node_destroy$FUNC
    );
}


