// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final FunctionDescriptor yr_compiler_load_atom_quality_table$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle yr_compiler_load_atom_quality_table$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_load_atom_quality_table",
        constants$101.yr_compiler_load_atom_quality_table$FUNC
    );
    static final FunctionDescriptor yr_compiler_add_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_add_file$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_add_file",
        constants$101.yr_compiler_add_file$FUNC
    );
    static final FunctionDescriptor yr_compiler_add_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_add_fd$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_add_fd",
        constants$101.yr_compiler_add_fd$FUNC
    );
    static final FunctionDescriptor yr_compiler_add_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_add_string$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_add_string",
        constants$101.yr_compiler_add_string$FUNC
    );
    static final FunctionDescriptor yr_compiler_get_error_message$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_compiler_get_error_message$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_get_error_message",
        constants$101.yr_compiler_get_error_message$FUNC
    );
    static final FunctionDescriptor yr_compiler_get_current_file_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_compiler_get_current_file_name$MH = RuntimeHelper.downcallHandle(
        "yr_compiler_get_current_file_name",
        constants$101.yr_compiler_get_current_file_name$FUNC
    );
}


