// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final FunctionDescriptor cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle cosf$MH = RuntimeHelper.downcallHandle(
        "cosf",
        constants$132.cosf$FUNC
    );
    static final FunctionDescriptor __cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __cosf$MH = RuntimeHelper.downcallHandle(
        "__cosf",
        constants$132.__cosf$FUNC
    );
    static final FunctionDescriptor sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle sinf$MH = RuntimeHelper.downcallHandle(
        "sinf",
        constants$132.sinf$FUNC
    );
    static final FunctionDescriptor __sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __sinf$MH = RuntimeHelper.downcallHandle(
        "__sinf",
        constants$132.__sinf$FUNC
    );
    static final FunctionDescriptor tanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle tanf$MH = RuntimeHelper.downcallHandle(
        "tanf",
        constants$132.tanf$FUNC
    );
    static final FunctionDescriptor __tanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __tanf$MH = RuntimeHelper.downcallHandle(
        "__tanf",
        constants$132.__tanf$FUNC
    );
}


