// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final FunctionDescriptor __lgammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __lgammaf$MH = RuntimeHelper.downcallHandle(
        "__lgammaf",
        constants$146.__lgammaf$FUNC
    );
    static final FunctionDescriptor tgammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle tgammaf$MH = RuntimeHelper.downcallHandle(
        "tgammaf",
        constants$146.tgammaf$FUNC
    );
    static final FunctionDescriptor __tgammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __tgammaf$MH = RuntimeHelper.downcallHandle(
        "__tgammaf",
        constants$146.__tgammaf$FUNC
    );
    static final FunctionDescriptor gammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gammaf$MH = RuntimeHelper.downcallHandle(
        "gammaf",
        constants$146.gammaf$FUNC
    );
    static final FunctionDescriptor __gammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __gammaf$MH = RuntimeHelper.downcallHandle(
        "__gammaf",
        constants$146.__gammaf$FUNC
    );
    static final FunctionDescriptor lgammaf_r$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lgammaf_r$MH = RuntimeHelper.downcallHandle(
        "lgammaf_r",
        constants$146.lgammaf_r$FUNC
    );
}


