// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final FunctionDescriptor __fma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fma$MH = RuntimeHelper.downcallHandle(
        "__fma",
        constants$129.__fma$FUNC
    );
    static final FunctionDescriptor scalb$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle scalb$MH = RuntimeHelper.downcallHandle(
        "scalb",
        constants$129.scalb$FUNC
    );
    static final FunctionDescriptor __scalb$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __scalb$MH = RuntimeHelper.downcallHandle(
        "__scalb",
        constants$129.__scalb$FUNC
    );
    static final FunctionDescriptor __fpclassifyf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fpclassifyf$MH = RuntimeHelper.downcallHandle(
        "__fpclassifyf",
        constants$129.__fpclassifyf$FUNC
    );
    static final FunctionDescriptor __signbitf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __signbitf$MH = RuntimeHelper.downcallHandle(
        "__signbitf",
        constants$129.__signbitf$FUNC
    );
    static final FunctionDescriptor __isinff$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __isinff$MH = RuntimeHelper.downcallHandle(
        "__isinff",
        constants$129.__isinff$FUNC
    );
}


