// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$91 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$91() {}
    static final FunctionDescriptor YR_ITERATOR_NEXT_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_ITERATOR_NEXT_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$91.YR_ITERATOR_NEXT_FUNC$FUNC
    );
    static final FunctionDescriptor RE_MATCH_CALLBACK_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RE_MATCH_CALLBACK_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$91.RE_MATCH_CALLBACK_FUNC$FUNC
    );
    static final FunctionDescriptor yr_re_ast_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_create$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_create",
        constants$91.yr_re_ast_create$FUNC
    );
    static final FunctionDescriptor yr_re_ast_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_destroy$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_destroy",
        constants$91.yr_re_ast_destroy$FUNC
    );
    static final FunctionDescriptor yr_re_ast_print$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_ast_print$MH = RuntimeHelper.downcallHandle(
        "yr_re_ast_print",
        constants$91.yr_re_ast_print$FUNC
    );
}


