// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final FunctionDescriptor __lgammaf_r$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __lgammaf_r$MH = RuntimeHelper.downcallHandle(
        "__lgammaf_r",
        constants$147.__lgammaf_r$FUNC
    );
    static final FunctionDescriptor rintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle rintf$MH = RuntimeHelper.downcallHandle(
        "rintf",
        constants$147.rintf$FUNC
    );
    static final FunctionDescriptor __rintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __rintf$MH = RuntimeHelper.downcallHandle(
        "__rintf",
        constants$147.__rintf$FUNC
    );
    static final FunctionDescriptor nextafterf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nextafterf$MH = RuntimeHelper.downcallHandle(
        "nextafterf",
        constants$147.nextafterf$FUNC
    );
    static final FunctionDescriptor __nextafterf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __nextafterf$MH = RuntimeHelper.downcallHandle(
        "__nextafterf",
        constants$147.__nextafterf$FUNC
    );
    static final FunctionDescriptor remainderf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle remainderf$MH = RuntimeHelper.downcallHandle(
        "remainderf",
        constants$147.remainderf$FUNC
    );
}


