// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final FunctionDescriptor yr_filemap_map_ex$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_filemap_map_ex$MH = RuntimeHelper.downcallHandle(
        "yr_filemap_map_ex",
        constants$97.yr_filemap_map_ex$FUNC
    );
    static final FunctionDescriptor yr_filemap_unmap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_filemap_unmap$MH = RuntimeHelper.downcallHandle(
        "yr_filemap_unmap",
        constants$97.yr_filemap_unmap$FUNC
    );
    static final FunctionDescriptor yr_filemap_unmap_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_filemap_unmap_fd$MH = RuntimeHelper.downcallHandle(
        "yr_filemap_unmap_fd",
        constants$97.yr_filemap_unmap_fd$FUNC
    );
    static final FunctionDescriptor YR_COMPILER_CALLBACK_FUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_COMPILER_CALLBACK_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$97.YR_COMPILER_CALLBACK_FUNC$FUNC
    );
    static final FunctionDescriptor YR_COMPILER_INCLUDE_CALLBACK_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


