// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$138 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$138() {}
    static final FunctionDescriptor exp2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle exp2f$MH = RuntimeHelper.downcallHandle(
        "exp2f",
        constants$138.exp2f$FUNC
    );
    static final FunctionDescriptor __exp2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __exp2f$MH = RuntimeHelper.downcallHandle(
        "__exp2f",
        constants$138.__exp2f$FUNC
    );
    static final FunctionDescriptor log2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle log2f$MH = RuntimeHelper.downcallHandle(
        "log2f",
        constants$138.log2f$FUNC
    );
    static final FunctionDescriptor __log2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __log2f$MH = RuntimeHelper.downcallHandle(
        "__log2f",
        constants$138.__log2f$FUNC
    );
    static final FunctionDescriptor powf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle powf$MH = RuntimeHelper.downcallHandle(
        "powf",
        constants$138.powf$FUNC
    );
    static final FunctionDescriptor __powf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __powf$MH = RuntimeHelper.downcallHandle(
        "__powf",
        constants$138.__powf$FUNC
    );
}


