// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$111 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$111() {}
    static final FunctionDescriptor exp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle exp$MH = RuntimeHelper.downcallHandle(
        "exp",
        constants$111.exp$FUNC
    );
    static final FunctionDescriptor __exp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __exp$MH = RuntimeHelper.downcallHandle(
        "__exp",
        constants$111.__exp$FUNC
    );
    static final FunctionDescriptor frexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle frexp$MH = RuntimeHelper.downcallHandle(
        "frexp",
        constants$111.frexp$FUNC
    );
    static final FunctionDescriptor __frexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __frexp$MH = RuntimeHelper.downcallHandle(
        "__frexp",
        constants$111.__frexp$FUNC
    );
    static final FunctionDescriptor ldexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ldexp$MH = RuntimeHelper.downcallHandle(
        "ldexp",
        constants$111.ldexp$FUNC
    );
    static final FunctionDescriptor __ldexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __ldexp$MH = RuntimeHelper.downcallHandle(
        "__ldexp",
        constants$111.__ldexp$FUNC
    );
}


