// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*pthread_key_create$__destr_function)(void*);
 * }
 */
public interface pthread_key_create$__destr_function {

    void apply(java.lang.foreign.MemorySegment _x0);
    static MemorySegment allocate(pthread_key_create$__destr_function fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(pthread_key_create$__destr_function.class, fi, constants$84.pthread_key_create$__destr_function$FUNC, scope);
    }
    static pthread_key_create$__destr_function ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment __x0) -> {
            try {
                constants$85.pthread_key_create$__destr_function$MH.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


