// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*YR_ATOMS_QUALITY_FUNC)(struct YR_ATOMS_CONFIG* config,struct YR_ATOM* atom);
 * }
 */
public interface YR_ATOMS_QUALITY_FUNC {

    int apply(java.lang.foreign.MemorySegment config, java.lang.foreign.MemorySegment atom);
    static MemorySegment allocate(YR_ATOMS_QUALITY_FUNC fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(YR_ATOMS_QUALITY_FUNC.class, fi, constants$94.YR_ATOMS_QUALITY_FUNC$FUNC, scope);
    }
    static YR_ATOMS_QUALITY_FUNC ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _config, java.lang.foreign.MemorySegment _atom) -> {
            try {
                return (int)constants$94.YR_ATOMS_QUALITY_FUNC$MH.invokeExact(symbol, _config, _atom);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


