// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*YR_EXT_INITIALIZE_FUNC)(struct YR_MODULE* module);
 * }
 */
public interface YR_EXT_INITIALIZE_FUNC {

    int apply(java.lang.foreign.MemorySegment module_object);
    static MemorySegment allocate(YR_EXT_INITIALIZE_FUNC fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(YR_EXT_INITIALIZE_FUNC.class, fi, constants$164.YR_EXT_INITIALIZE_FUNC$FUNC, scope);
    }
    static YR_EXT_INITIALIZE_FUNC ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _module_object) -> {
            try {
                return (int)constants$164.YR_EXT_INITIALIZE_FUNC$MH.invokeExact(symbol, _module_object);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


