// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_OBJECT_STRUCTURE {
 *     int canary;
 *     int8_t type;
 *     char* identifier;
 *     YR_OBJECT* parent;
 *     void* data;
 *     YR_STRUCTURE_MEMBER* members;
 * };
 * }
 */
public class YR_OBJECT_STRUCTURE {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("canary"),
        Constants$root.C_CHAR$LAYOUT.withName("type"),
        MemoryLayout.paddingLayout(24),
        Constants$root.C_POINTER$LAYOUT.withName("identifier"),
        Constants$root.C_POINTER$LAYOUT.withName("parent"),
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_POINTER$LAYOUT.withName("members")
    ).withName("YR_OBJECT_STRUCTURE");
    public static MemoryLayout $LAYOUT() {
        return YR_OBJECT_STRUCTURE.$struct$LAYOUT;
    }
    static final VarHandle canary$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("canary"));
    public static VarHandle canary$VH() {
        return YR_OBJECT_STRUCTURE.canary$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int canary;
     * }
     */
    public static int canary$get(MemorySegment seg) {
        return (int)YR_OBJECT_STRUCTURE.canary$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int canary;
     * }
     */
    public static void canary$set(MemorySegment seg, int x) {
        YR_OBJECT_STRUCTURE.canary$VH.set(seg, x);
    }
    public static int canary$get(MemorySegment seg, long index) {
        return (int)YR_OBJECT_STRUCTURE.canary$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void canary$set(MemorySegment seg, long index, int x) {
        YR_OBJECT_STRUCTURE.canary$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return YR_OBJECT_STRUCTURE.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int8_t type;
     * }
     */
    public static byte type$get(MemorySegment seg) {
        return (byte)YR_OBJECT_STRUCTURE.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int8_t type;
     * }
     */
    public static void type$set(MemorySegment seg, byte x) {
        YR_OBJECT_STRUCTURE.type$VH.set(seg, x);
    }
    public static byte type$get(MemorySegment seg, long index) {
        return (byte)YR_OBJECT_STRUCTURE.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, byte x) {
        YR_OBJECT_STRUCTURE.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle identifier$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("identifier"));
    public static VarHandle identifier$VH() {
        return YR_OBJECT_STRUCTURE.identifier$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* identifier;
     * }
     */
    public static MemorySegment identifier$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.identifier$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* identifier;
     * }
     */
    public static void identifier$set(MemorySegment seg, MemorySegment x) {
        YR_OBJECT_STRUCTURE.identifier$VH.set(seg, x);
    }
    public static MemorySegment identifier$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.identifier$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void identifier$set(MemorySegment seg, long index, MemorySegment x) {
        YR_OBJECT_STRUCTURE.identifier$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle parent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("parent"));
    public static VarHandle parent$VH() {
        return YR_OBJECT_STRUCTURE.parent$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_OBJECT* parent;
     * }
     */
    public static MemorySegment parent$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.parent$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_OBJECT* parent;
     * }
     */
    public static void parent$set(MemorySegment seg, MemorySegment x) {
        YR_OBJECT_STRUCTURE.parent$VH.set(seg, x);
    }
    public static MemorySegment parent$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.parent$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void parent$set(MemorySegment seg, long index, MemorySegment x) {
        YR_OBJECT_STRUCTURE.parent$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return YR_OBJECT_STRUCTURE.data$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.data$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        YR_OBJECT_STRUCTURE.data$VH.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        YR_OBJECT_STRUCTURE.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle members$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("members"));
    public static VarHandle members$VH() {
        return YR_OBJECT_STRUCTURE.members$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_STRUCTURE_MEMBER* members;
     * }
     */
    public static MemorySegment members$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.members$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_STRUCTURE_MEMBER* members;
     * }
     */
    public static void members$set(MemorySegment seg, MemorySegment x) {
        YR_OBJECT_STRUCTURE.members$VH.set(seg, x);
    }
    public static MemorySegment members$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_OBJECT_STRUCTURE.members$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void members$set(MemorySegment seg, long index, MemorySegment x) {
        YR_OBJECT_STRUCTURE.members$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


