// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_RULE_PROFILING_INFO {
 *     YR_RULE* rule;
 *     uint64_t cost;
 * };
 * }
 */
public class YR_RULE_PROFILING_INFO {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("rule"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("cost")
    ).withName("YR_RULE_PROFILING_INFO");
    public static MemoryLayout $LAYOUT() {
        return YR_RULE_PROFILING_INFO.$struct$LAYOUT;
    }
    static final VarHandle rule$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("rule"));
    public static VarHandle rule$VH() {
        return YR_RULE_PROFILING_INFO.rule$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_RULE* rule;
     * }
     */
    public static MemorySegment rule$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE_PROFILING_INFO.rule$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_RULE* rule;
     * }
     */
    public static void rule$set(MemorySegment seg, MemorySegment x) {
        YR_RULE_PROFILING_INFO.rule$VH.set(seg, x);
    }
    public static MemorySegment rule$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE_PROFILING_INFO.rule$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rule$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE_PROFILING_INFO.rule$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle cost$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cost"));
    public static VarHandle cost$VH() {
        return YR_RULE_PROFILING_INFO.cost$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t cost;
     * }
     */
    public static long cost$get(MemorySegment seg) {
        return (long)YR_RULE_PROFILING_INFO.cost$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t cost;
     * }
     */
    public static void cost$set(MemorySegment seg, long x) {
        YR_RULE_PROFILING_INFO.cost$VH.set(seg, x);
    }
    public static long cost$get(MemorySegment seg, long index) {
        return (long)YR_RULE_PROFILING_INFO.cost$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cost$set(MemorySegment seg, long index, long x) {
        YR_RULE_PROFILING_INFO.cost$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


