// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct YR_RULE {
 *     int32_t flags;
 *     int32_t num_atoms;
 *     union {
 *         char* identifier;
 *         YR_ARENA_REF identifier_;
 *     };
 *     union {
 *         char* tags;
 *         YR_ARENA_REF tags_;
 *     };
 *     union {
 *         YR_META* metas;
 *         YR_ARENA_REF metas_;
 *     };
 *     union {
 *         YR_STRING* strings;
 *         YR_ARENA_REF strings_;
 *     };
 *     union {
 *         YR_NAMESPACE* ns;
 *         YR_ARENA_REF ns_;
 *     };
 * };
 * }
 */
public class YR_RULE {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("flags"),
        Constants$root.C_INT$LAYOUT.withName("num_atoms"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("identifier"),
            MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("buffer_id"),
                Constants$root.C_INT$LAYOUT.withName("offset")
            ).withName("identifier_")
        ).withName("$anon$0"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("tags"),
            MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("buffer_id"),
                Constants$root.C_INT$LAYOUT.withName("offset")
            ).withName("tags_")
        ).withName("$anon$1"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("metas"),
            MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("buffer_id"),
                Constants$root.C_INT$LAYOUT.withName("offset")
            ).withName("metas_")
        ).withName("$anon$2"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("strings"),
            MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("buffer_id"),
                Constants$root.C_INT$LAYOUT.withName("offset")
            ).withName("strings_")
        ).withName("$anon$3"),
        MemoryLayout.unionLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ns"),
            MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("buffer_id"),
                Constants$root.C_INT$LAYOUT.withName("offset")
            ).withName("ns_")
        ).withName("$anon$4")
    ).withName("YR_RULE");
    public static MemoryLayout $LAYOUT() {
        return YR_RULE.$struct$LAYOUT;
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return YR_RULE.flags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)YR_RULE.flags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        YR_RULE.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)YR_RULE.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        YR_RULE.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle num_atoms$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_atoms"));
    public static VarHandle num_atoms$VH() {
        return YR_RULE.num_atoms$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t num_atoms;
     * }
     */
    public static int num_atoms$get(MemorySegment seg) {
        return (int)YR_RULE.num_atoms$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t num_atoms;
     * }
     */
    public static void num_atoms$set(MemorySegment seg, int x) {
        YR_RULE.num_atoms$VH.set(seg, x);
    }
    public static int num_atoms$get(MemorySegment seg, long index) {
        return (int)YR_RULE.num_atoms$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_atoms$set(MemorySegment seg, long index, int x) {
        YR_RULE.num_atoms$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle identifier$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("identifier"));
    public static VarHandle identifier$VH() {
        return YR_RULE.identifier$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* identifier;
     * }
     */
    public static MemorySegment identifier$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE.identifier$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* identifier;
     * }
     */
    public static void identifier$set(MemorySegment seg, MemorySegment x) {
        YR_RULE.identifier$VH.set(seg, x);
    }
    public static MemorySegment identifier$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE.identifier$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void identifier$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE.identifier$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment identifier_$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    static final VarHandle tags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$1"), MemoryLayout.PathElement.groupElement("tags"));
    public static VarHandle tags$VH() {
        return YR_RULE.tags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* tags;
     * }
     */
    public static MemorySegment tags$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE.tags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* tags;
     * }
     */
    public static void tags$set(MemorySegment seg, MemorySegment x) {
        YR_RULE.tags$VH.set(seg, x);
    }
    public static MemorySegment tags$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE.tags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tags$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE.tags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment tags_$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    static final VarHandle metas$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("metas"));
    public static VarHandle metas$VH() {
        return YR_RULE.metas$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_META* metas;
     * }
     */
    public static MemorySegment metas$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE.metas$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_META* metas;
     * }
     */
    public static void metas$set(MemorySegment seg, MemorySegment x) {
        YR_RULE.metas$VH.set(seg, x);
    }
    public static MemorySegment metas$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE.metas$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void metas$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE.metas$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment metas_$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    static final VarHandle strings$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$3"), MemoryLayout.PathElement.groupElement("strings"));
    public static VarHandle strings$VH() {
        return YR_RULE.strings$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_STRING* strings;
     * }
     */
    public static MemorySegment strings$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE.strings$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_STRING* strings;
     * }
     */
    public static void strings$set(MemorySegment seg, MemorySegment x) {
        YR_RULE.strings$VH.set(seg, x);
    }
    public static MemorySegment strings$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE.strings$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strings$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE.strings$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment strings_$slice(MemorySegment seg) {
        return seg.asSlice(32, 8);
    }
    static final VarHandle ns$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$4"), MemoryLayout.PathElement.groupElement("ns"));
    public static VarHandle ns$VH() {
        return YR_RULE.ns$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * YR_NAMESPACE* ns;
     * }
     */
    public static MemorySegment ns$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)YR_RULE.ns$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * YR_NAMESPACE* ns;
     * }
     */
    public static void ns$set(MemorySegment seg, MemorySegment x) {
        YR_RULE.ns$VH.set(seg, x);
    }
    public static MemorySegment ns$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)YR_RULE.ns$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ns$set(MemorySegment seg, long index, MemorySegment x) {
        YR_RULE.ns$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ns_$slice(MemorySegment seg) {
        return seg.asSlice(40, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


