// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct YR_SCAN_CONTEXT YR_SCANNER;
 * }
 */
public final class YR_SCANNER extends YR_SCAN_CONTEXT {

    // Suppresses default constructor, ensuring non-instantiability.
    private YR_SCANNER() {}
}


